/**
 * tepui — org compiler
 *
 * org.yaml (core archetypes) + org.overlay.yaml (company) + loops/(*)/policy.yaml
 *   -> <company>/generated/{agents,skills,hooks,plugins}.json5 + budgets.json
 *
 * Two properties make this load-bearing rather than convenient:
 *
 *   1. The output is COMMITTED, so a permission change is a reviewable PR diff.
 *      `--check` asserts the compiler is idempotent (CI runs it, then
 *      `git diff --exit-code`).
 *   2. It FAILS CLOSED. Every invariant below refuses to emit rather than
 *      emitting something permissive. A compiler that warns is a compiler that
 *      gets ignored.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const HERE = dirname(fileURLToPath(import.meta.url));
const CORE = process.env.TEPUI_CORE ? resolve(process.env.TEPUI_CORE) : resolve(HERE, "../..");

type Sandbox = { mode: "off" | "non-main" | "all"; workspace_access: "none" | "ro" | "rw" };
type Budget = { per_run_usd: number; per_day_usd: number };

type Archetype = {
  title: string;
  reports_to?: string;
  system_agent?: boolean;
  model?: string;
  utility_model?: string;
  sandbox?: Sandbox;
  sandbox_justification?: string;
  reads_untrusted_input?: boolean;
  tools?: { profile: string; deny?: string[]; allow?: string[] };
  credentials?: string[];
  budget?: Budget;
  subagents?: Record<string, number>;
};

class CompileError extends Error {
  failures: string[];
  constructor(failures: string[]) {
    super(`${failures.length} invariant violation(s)`);
    this.failures = failures;
  }
}

const readYaml = <T,>(p: string): T => parseYaml(readFileSync(p, "utf8")) as T;

/**
 * tepui uses SEMANTIC profile names in org.yaml (portable, self-describing).
 * The runtime accepts only four: minimal | coding | messaging | full. Mapping
 * them here is exactly what the adapter layer is for — org.yaml never learns
 * a runtime's vocabulary.
 */
/**
 * Context windows and USD-per-million-token costs for non-Anthropic models.
 * UNPRICED is deliberately expensive: an unpriced model must never look free
 * to the budget gate, so it is charged at a rate that will trip a cap early.
 * Replace these with published figures once confirmed.
 */
const UNPRICED = { input: 15, output: 60, cacheRead: 15, cacheWrite: 15 };
const MODEL_CONTEXT: Record<string, number> = {
  "nvidia/nemotron-3-ultra-550b-a55b": 128_000,
  "nvidia/nemotron-3-super-120b-a12b": 128_000,
  "nvidia/nemotron-3-nano-30b-a3b": 128_000,
};
const MODEL_COST: Record<string, { input: number; output: number; cacheRead: number; cacheWrite: number }> = {
  "nvidia/nemotron-3-nano-30b-a3b":    { input: 0.05,  output: 0.20, cacheRead: 0.025, cacheWrite: 0.05 },
  "nvidia/nemotron-3-super-120b-a12b": { input: 0.085, output: 0.40, cacheRead: 0.085, cacheWrite: 0.085 },
  "nvidia/nemotron-3-ultra-550b-a55b": { input: 0.50,  output: 2.20, cacheRead: 0.10,  cacheWrite: 0.50 },
};

const PROFILE_MAP: Record<string, { profile: string; deny: string[] }> = {
  ops:        { profile: "full",    deny: [] },
  readonly:   { profile: "minimal", deny: ["write", "edit", "apply_patch", "exec"] },
  authoring:  { profile: "coding",  deny: ["exec", "browser"] },
  quarantine: { profile: "minimal", deny: ["exec", "write", "edit", "apply_patch", "message", "browser", "web_fetch"] },
  coding:     { profile: "coding",  deny: [] },
};

/** JSON5-ish emitter: plain JSON is valid JSON5, plus a provenance banner. */
function emit(path: string, value: unknown, source: string) {
  const banner =
    `// GENERATED by runtime/openclaw/compile.ts — DO NOT EDIT BY HAND.\n` +
    `// Source: ${source}\n` +
    `// Edit the source and re-run \`pnpm compile\`. This file is committed so\n` +
    `// that permission changes show up as a reviewable diff.\n`;
  writeFileSync(path, banner + JSON.stringify(value, null, 2) + "\n");
}

export function compile(companyDir: string, opts: { workspaceRoot?: string; outDir?: string } = {}) {
  const failures: string[] = [];
  const fail = (msg: string) => failures.push(msg);

  const core = readYaml<{ defaults: Partial<Archetype>; archetypes: Record<string, Archetype>; tiers: Record<string, unknown> }>(
    join(CORE, "org.yaml"),
  );
  const overlay = readYaml<{
    paths?: { workspace_root: string };
    provider?: { id: string; api: string; base_url: string; api_key_env: string; tier?: string };
    tiers: Record<string, string>;
    employees: Record<string, { archetype: string; name: string; model?: string; slack_account?: string; slack_channels?: string[]; credentials?: string[] }>;
    loops: Record<string, { enabled: boolean }>;
  }>(join(companyDir, "org.overlay.yaml"));

  // ---- loops -------------------------------------------------------------
  const loopsDir = join(CORE, "loops");
  const loops: Record<string, any> = {};
  for (const name of readdirSync(loopsDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)) {
    const policyPath = join(loopsDir, name, "policy.yaml");
    if (!existsSync(policyPath)) {
      fail(`loop '${name}' has no policy.yaml — every loop must declare its capabilities`);
      continue;
    }
    loops[name] = readYaml(policyPath);

    // INVARIANT: approvals must have a workflow that implements them.
    const approvals = loops[name].approvals ?? [];
    if (approvals.length > 0) {
      const wf = join(CORE, "runtime/openclaw/workflows", `${name}.lobster.yaml`);
      if (!existsSync(wf)) {
        fail(`loop '${name}' declares ${approvals.length} approval(s) but ${wf.replace(CORE + "/", "")} does not exist`);
      }
    }
  }

  // Credentials actually used, by owning agent.
  const credentialsNeededBy = new Map<string, Set<string>>();
  for (const [loopName, policy] of Object.entries<any>(loops)) {
    const owner = policy.owner;
    if (!owner) { fail(`loop '${loopName}' declares no owner agent`); continue; }
    const set = credentialsNeededBy.get(owner) ?? new Set<string>();
    for (const c of policy.capabilities?.credentials ?? []) set.add(c);
    credentialsNeededBy.set(owner, set);
  }

  // A deployment may override where workspaces live (container vs bare metal)
  // without changing the committed overlay. Same behaviour, different host.
  const wsRoot = opts.workspaceRoot ?? overlay.paths?.workspace_root;
  if (!wsRoot) fail("org.overlay.yaml must declare paths.workspace_root — the compiler will not guess where agent workspaces live");

  // ---- agents ------------------------------------------------------------
  const agents: Record<string, any> = {};
  const budgets: Record<string, Budget> = {};
  const skills: Record<string, any> = {};

  for (const [id, emp] of Object.entries(overlay.employees)) {
    const arch = core.archetypes[emp.archetype];
    if (!arch) { fail(`employee '${id}' references unknown archetype '${emp.archetype}'`); continue; }

    const merged: Archetype = { ...core.defaults, ...arch };
    const credentials = emp.credentials ?? arch.credentials ?? [];

    // INVARIANT 1: an explicit sandbox block, always. The upstream docs
    // contradict each other on the default, so we never inherit one.
    if (!merged.sandbox?.mode || !merged.sandbox?.workspace_access) {
      fail(`agent '${id}' has no explicit sandbox block (mode + workspace_access). Never rely on the runtime default.`);
    }

    // INVARIANT 2: sandbox:off is an escape hatch that must be argued for.
    if (merged.sandbox?.mode === "off" && !merged.sandbox_justification) {
      fail(`agent '${id}' sets sandbox.mode=off without a sandbox_justification`);
    }

    // INVARIANT 3 — the intake invariant. Untrusted input and credentials must
    // never coexist in one agent. This is the whole prompt-injection defence.
    if (merged.reads_untrusted_input) {
      if (credentials.length > 0) {
        fail(`agent '${id}' reads untrusted input but holds credentials [${credentials.join(", ")}]. An injection here would control them.`);
      }
      if (merged.sandbox?.mode !== "all" || merged.sandbox?.workspace_access !== "none") {
        fail(`agent '${id}' reads untrusted input and must run sandbox.mode=all with workspace_access=none`);
      }
      const semantic = merged.tools?.profile ?? "minimal";
      const effective = new Set([...(PROFILE_MAP[semantic]?.deny ?? []), ...(merged.tools?.deny ?? [])]);
      for (const t of ["exec", "write", "edit", "message", "web_fetch", "browser"]) {
        if (!effective.has(t)) fail(`agent '${id}' reads untrusted input and must deny '${t}' (effective denies: ${[...effective].join(", ") || "none"})`);
      }
    }

    // INVARIANT 4: no credential grant broader than what its loops actually use.
    const needed = credentialsNeededBy.get(id) ?? new Set<string>();
    for (const c of credentials) {
      if (!needed.has(c)) {
        fail(`agent '${id}' is granted '${c}' but no loop it owns declares it. Remove the grant or declare the need.`);
      }
    }

    const modelTier = emp.model ?? merged.model!;
    const model = overlay.tiers[modelTier] ?? modelTier;
    const utility = overlay.tiers[merged.utility_model!] ?? merged.utility_model;

    // reports_to compiles into delegation allowlists — the org chart made real.
    const reports = Object.entries(overlay.employees)
      .filter(([, e]) => core.archetypes[e.archetype]?.reports_to === id)
      .map(([subId]) => subId);

    agents[id] = {
      id,
      name: emp.name,
      identity: { name: emp.name },
      workspace: `${wsRoot}/agents/${id}`,
      agentDir: `${wsRoot}/agents/${id}/.agent`,
      model,
      utilityModel: utility,
      sandbox: { mode: merged.sandbox?.mode, backend: "docker", workspaceAccess: merged.sandbox?.workspace_access },
      // An explicit list REPLACES the runtime defaults entirely, which is why
      // every agent gets an exhaustive one and inherits nothing.
      skills: Object.entries(loops).filter(([, p]) => p.owner === id).map(([n]) => n),
      tools: (() => {
        const semantic = merged.tools?.profile ?? "minimal";
        const mapped = PROFILE_MAP[semantic];
        if (!mapped) { fail(`agent '${id}' uses unknown tool profile '${semantic}' (known: ${Object.keys(PROFILE_MAP).join(", ")})`); return {}; }
        // Union of the profile's baseline denies and the agent's own — deny wins.
        const deny = [...new Set([...mapped.deny, ...(merged.tools?.deny ?? [])])];
        return { profile: mapped.profile, deny, ...(merged.tools?.allow ? { allow: merged.tools.allow } : {}) };
      })(),
      // Per-agent subagents only carries the allowlist; the numeric caps live in
      // agents.defaults per the shipped schema.
      subagents: { allowAgents: reports, requireAgentId: true },
      ...(merged.system_agent ? { default: true } : {}),
    };

    budgets[id] = { ...(core.defaults.budget as Budget), ...(arch.budget ?? {}) };

    for (const c of credentials) {
      const loopName = Object.entries<any>(loops).find(([, p]) => p.owner === id && (p.capabilities?.credentials ?? []).includes(c))?.[0];
      if (loopName) {
        skills[loopName] = skills[loopName] ?? { env: {} };
        skills[loopName].env[c] = `\${${c}}`;   // resolved from the gitignored .env
      }
    }
  }

  // INVARIANT: an evaluation-tier provider may never serve a loop that handles
  // real company data. NVIDIA's trial ToS makes prompts and outputs training
  // data and prohibits personal/financial information — a company OS is made
  // of exactly that. This turns "switch before it matters" into a build error.
  if (overlay.provider?.tier === "evaluation") {
    for (const [loopName, policy] of Object.entries<any>(loops)) {
      if (policy.handles_company_data) {
        fail(`loop '${loopName}' is marked handles_company_data but provider '${overlay.provider.id}' is tier=evaluation. ` +
             `Its ToS permits internal testing only, collects prompts and outputs as training data, and prohibits ` +
             `personal/financial information. Switch to a commercial endpoint before enabling this loop.`);
      }
    }
    if ((overlay.employees && Object.values(overlay.employees).some((e: any) => (e.credentials ?? []).length > 0))) {
      fail(`provider '${overlay.provider.id}' is tier=evaluation but agents hold credentials. ` +
           `Real credentials imply real data. Switch to a commercial endpoint first.`);
    }
  }

  // ---- Slack bindings ----------------------------------------------------
  // Routing is deterministic and most-specific-first. Every bound channel gets
  // requireMention so the agent does not respond to every message in a shared
  // channel — in a workspace with humans that is the difference between a
  // colleague and a nuisance.
  // Two routing dimensions, and they compose:
  //
  //   slack_account  -> a DEDICATED Slack app, so the agent has its own
  //                     @handle. This is the only way to @ an individual agent,
  //                     because in Slack one app == one bot user == one handle.
  //                     It also makes the capability boundary visible: you
  //                     invite @tepui-marketing only to channels where
  //                     marketing should operate, so Slack channel membership
  //                     becomes an access-control layer matching the org chart.
  //
  //   slack_channels -> channel-scoped routing on a SHARED app. Cheaper to set
  //                     up (one app, two tokens) but you address the app, not
  //                     the agent.
  const bindings: any[] = [];
  const slackChannels: Record<string, any> = {};
  const slackAccounts: Record<string, any> = {};

  // An employee with slack_channels but no slack_account rides the SHARED
  // "default" app: one integration for the whole company, and the CHANNEL
  // decides which agent answers. Cheapest to set up (1 app, 2 tokens); you
  // address the app rather than the agent.
  const usesShared = Object.values(overlay.employees).some((e) => !e.slack_account && (e.slack_channels ?? []).length);
  if (usesShared) {
    slackAccounts["default"] = {
      botToken: { source: "env", provider: "default", id: "SLACK_BOT_TOKEN" },
      appToken: { source: "env", provider: "default", id: "SLACK_APP_TOKEN" },
    };
  }

  for (const [id, emp] of Object.entries(overlay.employees)) {
    const account = emp.slack_account;

    if (!account && !(emp.slack_channels ?? []).length) {
      // no Slack surface at all — reported below, never fatal
    }

    if (account) {
      if (!/^[a-z0-9][a-z0-9_-]*$/.test(account)) {
        fail(`employee '${id}' has slack_account '${account}' — use a lowercase slug; it names env vars`);
        continue;
      }
      const up = account.toUpperCase().replace(/-/g, "_");
      slackAccounts[account] = {
        botToken: { source: "env", provider: "default", id: `SLACK_BOT_TOKEN_${up}` },
        appToken: { source: "env", provider: "default", id: `SLACK_APP_TOKEN_${up}` },
      };
      // Account-scoped: this agent answers to its own handle anywhere it is invited.
      bindings.push({ agentId: id, comment: `slack app '${account}' -> ${id}`, match: { channel: "slack", accountId: account } });
    }

    for (const ch of emp.slack_channels ?? []) {
      if (!/^C[A-Z0-9]+$/.test(ch)) {
        fail(`employee '${id}' has slack channel '${ch}' — use the immutable channel ID (C...), not the name`);
        continue;
      }
      // Channel rules are narrower than account rules, so they are emitted
      // first: within a tier, config order wins.
      bindings.unshift({
        agentId: id, comment: `#${ch} -> ${id}`,
        match: { channel: "slack", ...(account ? { accountId: account } : {}), peer: { kind: "channel", id: ch } },
      });
      slackChannels[ch] = { enabled: true, requireMention: true };
    }
  }

  // An agent with neither is unreachable from Slack — usually a mistake worth
  // surfacing, but never fatal (intake is reached by delegation, not directly).
  const reachable = new Set(bindings.map((b) => b.agentId));
  const unreachable = Object.keys(overlay.employees).filter((id) => !reachable.has(id));

  if (failures.length) throw new CompileError(failures);

  const outDir = opts.outDir ?? join(companyDir, "generated");
  mkdirSync(outDir, { recursive: true });
  const src = "org.yaml + org.overlay.yaml + loops/*/policy.yaml";

  // NOTE: `agents.list` is an ARRAY and `id` is required. The published docs
  // still show an `agents.entries` map — the shipped JSON schema is the
  // authority, and it disagrees. Re-check on every image bump; this is exactly
  // the fast-upstream tax PLAN.md budgets for.
  const sub = core.defaults.subagents as any ?? {};
  emit(join(outDir, "agents.json5"), {
    defaults: {
      subagents: {
        maxConcurrent: sub.max_concurrent,
        maxChildrenPerAgent: sub.max_children_per_agent,
        maxSpawnDepth: sub.max_spawn_depth,
      },
    },
    list: Object.values(agents),
  }, src);
  emit(join(outDir, "skills.json5"), { entries: skills }, src);
  emit(join(outDir, "bindings.json5"), bindings, src);
  if (Object.keys(slackAccounts).length || Object.keys(slackChannels).length) {
    emit(join(outDir, "channels.json5"), {
      slack: {
        enabled: true,
        mode: "socket",
        // Socket Mode: an OUTBOUND websocket per account. No public URL, no
        // ingress, works behind NAT — a laptop, a zero-ingress VM and a Mac
        // mini all behave identically.
        dmPolicy: "pairing",
        unfurlLinks: false,     // do not fetch attacker-supplied URLs
        ...(Object.keys(slackAccounts).length ? { accounts: slackAccounts } : {}),
        ...(Object.keys(slackChannels).length ? { channels: slackChannels } : {}),
      },
    }, src);
  }

  // Provider + model catalogue. The API KEY is never emitted — only a ${VAR}
  // reference that the runtime resolves from the gitignored .env. Costs are
  // declared here so the runtime's own accounting agrees with lib/budget.
  if (overlay.provider) {
    const p = overlay.provider;
    const modelIds = [...new Set(Object.values(overlay.tiers))];
    emit(join(outDir, "models.json5"), {
      providers: {
        [p.id]: {
          api: p.api,
          baseUrl: p.base_url,
          apiKey: `\${${p.api_key_env}}`,
          models: modelIds.map((full) => {
            const id = full.startsWith(`${p.id}/`) ? full.slice(p.id.length + 1) : full;
            return { id, name: id, contextTokens: MODEL_CONTEXT[full] ?? 128_000, cost: MODEL_COST[full] ?? UNPRICED };
          }),
        },
      },
    }, src);
  }
  emit(join(outDir, "budgets.json"), { perLoop: Object.fromEntries(Object.entries<any>(loops).map(([n, p]) => [n, p.budget])), perAgent: budgets }, src);

  return { agents: Object.keys(agents).length, loops: Object.keys(loops).length, slackAccounts: Object.keys(slackAccounts).length, unreachable };
}

export { CompileError };

// ---- CLI -----------------------------------------------------------------
// Guarded so tests can import compile() without triggering a run.
const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (invokedDirectly) {
const args = process.argv.slice(2);
const companyDir = resolve(args.find((a) => !a.startsWith("--")) ?? "../tepui-company");
const flag = (n: string) => { const i = args.indexOf(`--${n}`); return i >= 0 ? args[i + 1] : undefined; };
try {
  const r = compile(companyDir, { workspaceRoot: flag("workspace-root"), outDir: flag("out") });
  console.log(`compiled ${r.agents} agents, ${r.loops} loops` + (r.slackAccounts ? `, ${r.slackAccounts} slack app(s)` : "") + ` -> ${companyDir}/generated/`);
  if (r.unreachable.length) console.log(`  note: not reachable from Slack (delegation only): ${r.unreachable.join(", ")}`);
} catch (e) {
  if (e instanceof CompileError) {
    console.error(`\ncompile FAILED — refusing to emit:\n`);
    for (const f of e.failures) console.error(`  ✗ ${f}`);
    console.error();
    process.exit(1);
  }
  throw e;
}
}
