/**
 * tepui — org compiler
 *
 * org.yaml (core archetypes) + org.overlay.yaml (company) + loops/(*)/policy.yaml
 *   -> <company>/generated/{agents,skills,hooks,plugins}.json5 + budgets.json
 *
 * Two properties make this load-bearing rather than convenient:
 *
 *   1. The output is COMMITTED, so a permission change is a reviewable PR diff.
 *      `--check` asserts the compiler is idempotent (CI runs it, then
 *      `git diff --exit-code`).
 *   2. It FAILS CLOSED. Every invariant below refuses to emit rather than
 *      emitting something permissive. A compiler that warns is a compiler that
 *      gets ignored.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const HERE = dirname(fileURLToPath(import.meta.url));
const CORE = process.env.TEPUI_CORE ? resolve(process.env.TEPUI_CORE) : resolve(HERE, "../..");

type Sandbox = { mode: "off" | "non-main" | "all"; workspace_access: "none" | "ro" | "rw" };
type Budget = { per_run_usd: number; per_day_usd: number };

type Archetype = {
  title: string;
  reports_to?: string;
  system_agent?: boolean;
  model?: string;
  utility_model?: string;
  sandbox?: Sandbox;
  sandbox_justification?: string;
  reads_untrusted_input?: boolean;
  tools?: { profile: string; deny?: string[]; allow?: string[] };
  credentials?: string[];
  budget?: Budget;
  subagents?: Record<string, number>;
};

class CompileError extends Error {
  failures: string[];
  constructor(failures: string[]) {
    super(`${failures.length} invariant violation(s)`);
    this.failures = failures;
  }
}

const readYaml = <T,>(p: string): T => parseYaml(readFileSync(p, "utf8")) as T;

/**
 * tepui uses SEMANTIC profile names in org.yaml (portable, self-describing).
 * The runtime accepts only four: minimal | coding | messaging | full. Mapping
 * them here is exactly what the adapter layer is for — org.yaml never learns
 * a runtime's vocabulary.
 */
/**
 * Context windows and USD-per-million-token costs for non-Anthropic models.
 * UNPRICED is deliberately expensive: an unpriced model must never look free
 * to the budget gate, so it is charged at a rate that will trip a cap early.
 * Replace these with published figures once confirmed.
 */
const UNPRICED = { input: 15, output: 60, cacheRead: 15, cacheWrite: 15 };
const MODEL_CONTEXT: Record<string, number> = {
  "nvidia/nemotron-3-ultra-550b-a55b": 128_000,
  "nvidia/nemotron-3-super-120b-a12b": 128_000,
  "nvidia/nemotron-3-nano-30b-a3b": 128_000,
};
const MODEL_COST: Record<string, { input: number; output: number; cacheRead: number; cacheWrite: number }> = {
  "nvidia/nemotron-3-nano-30b-a3b":    { input: 0.05,  output: 0.20, cacheRead: 0.025, cacheWrite: 0.05 },
  "nvidia/nemotron-3-super-120b-a12b": { input: 0.085, output: 0.40, cacheRead: 0.085, cacheWrite: 0.085 },
  "nvidia/nemotron-3-ultra-550b-a55b": { input: 0.50,  output: 2.20, cacheRead: 0.10,  cacheWrite: 0.50 },
};

const PROFILE_MAP: Record<string, { profile: string; deny: string[] }> = {
  ops:        { profile: "full",    deny: [] },
  readonly:   { profile: "minimal", deny: ["write", "edit", "apply_patch", "exec"] },
  authoring:  { profile: "coding",  deny: ["exec", "browser"] },
  quarantine: { profile: "minimal", deny: ["exec", "write", "edit", "apply_patch", "message", "browser", "web_fetch"] },
  coding:     { profile: "coding",  deny: [] },
};

/** JSON5-ish emitter: plain JSON is valid JSON5, plus a provenance banner. */
function emit(path: string, value: unknown, source: string) {
  const banner =
    `// GENERATED by runtime/openclaw/compile.ts — DO NOT EDIT BY HAND.\n` +
    `// Source: ${source}\n` +
    `// Edit the source and re-run \`pnpm compile\`. This file is committed so\n` +
    `// that permission changes show up as a reviewable diff.\n`;
  writeFileSync(path, banner + JSON.stringify(value, null, 2) + "\n");
}

export function compile(companyDir: string) {
  const failures: string[] = [];
  const fail = (msg: string) => failures.push(msg);

  const core = readYaml<{ defaults: Partial<Archetype>; archetypes: Record<string, Archetype>; tiers: Record<string, unknown> }>(
    join(CORE, "org.yaml"),
  );
  const overlay = readYaml<{
    paths?: { workspace_root: string };
    provider?: { id: string; api: string; base_url: string; api_key_env: string };
    tiers: Record<string, string>;
    employees: Record<string, { archetype: string; name: string; model?: string; slack_channels?: string[]; credentials?: string[] }>;
    loops: Record<string, { enabled: boolean }>;
  }>(join(companyDir, "org.overlay.yaml"));

  // ---- loops -------------------------------------------------------------
  const loopsDir = join(CORE, "loops");
  const loops: Record<string, any> = {};
  for (const name of readdirSync(loopsDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)) {
    const policyPath = join(loopsDir, name, "policy.yaml");
    if (!existsSync(policyPath)) {
      fail(`loop '${name}' has no policy.yaml — every loop must declare its capabilities`);
      continue;
    }
    loops[name] = readYaml(policyPath);

    // INVARIANT: approvals must have a workflow that implements them.
    const approvals = loops[name].approvals ?? [];
    if (approvals.length > 0) {
      const wf = join(CORE, "runtime/openclaw/workflows", `${name}.lobster.yaml`);
      if (!existsSync(wf)) {
        fail(`loop '${name}' declares ${approvals.length} approval(s) but ${wf.replace(CORE + "/", "")} does not exist`);
      }
    }
  }

  // Credentials actually used, by owning agent.
  const credentialsNeededBy = new Map<string, Set<string>>();
  for (const [loopName, policy] of Object.entries<any>(loops)) {
    const owner = policy.owner;
    if (!owner) { fail(`loop '${loopName}' declares no owner agent`); continue; }
    const set = credentialsNeededBy.get(owner) ?? new Set<string>();
    for (const c of policy.capabilities?.credentials ?? []) set.add(c);
    credentialsNeededBy.set(owner, set);
  }

  const wsRoot = overlay.paths?.workspace_root;
  if (!wsRoot) fail("org.overlay.yaml must declare paths.workspace_root — the compiler will not guess where agent workspaces live");

  // ---- agents ------------------------------------------------------------
  const agents: Record<string, any> = {};
  const budgets: Record<string, Budget> = {};
  const skills: Record<string, any> = {};

  for (const [id, emp] of Object.entries(overlay.employees)) {
    const arch = core.archetypes[emp.archetype];
    if (!arch) { fail(`employee '${id}' references unknown archetype '${emp.archetype}'`); continue; }

    const merged: Archetype = { ...core.defaults, ...arch };
    const credentials = emp.credentials ?? arch.credentials ?? [];

    // INVARIANT 1: an explicit sandbox block, always. The upstream docs
    // contradict each other on the default, so we never inherit one.
    if (!merged.sandbox?.mode || !merged.sandbox?.workspace_access) {
      fail(`agent '${id}' has no explicit sandbox block (mode + workspace_access). Never rely on the runtime default.`);
    }

    // INVARIANT 2: sandbox:off is an escape hatch that must be argued for.
    if (merged.sandbox?.mode === "off" && !merged.sandbox_justification) {
      fail(`agent '${id}' sets sandbox.mode=off without a sandbox_justification`);
    }

    // INVARIANT 3 — the intake invariant. Untrusted input and credentials must
    // never coexist in one agent. This is the whole prompt-injection defence.
    if (merged.reads_untrusted_input) {
      if (credentials.length > 0) {
        fail(`agent '${id}' reads untrusted input but holds credentials [${credentials.join(", ")}]. An injection here would control them.`);
      }
      if (merged.sandbox?.mode !== "all" || merged.sandbox?.workspace_access !== "none") {
        fail(`agent '${id}' reads untrusted input and must run sandbox.mode=all with workspace_access=none`);
      }
      const semantic = merged.tools?.profile ?? "minimal";
      const effective = new Set([...(PROFILE_MAP[semantic]?.deny ?? []), ...(merged.tools?.deny ?? [])]);
      for (const t of ["exec", "write", "edit", "message", "web_fetch", "browser"]) {
        if (!effective.has(t)) fail(`agent '${id}' reads untrusted input and must deny '${t}' (effective denies: ${[...effective].join(", ") || "none"})`);
      }
    }

    // INVARIANT 4: no credential grant broader than what its loops actually use.
    const needed = credentialsNeededBy.get(id) ?? new Set<string>();
    for (const c of credentials) {
      if (!needed.has(c)) {
        fail(`agent '${id}' is granted '${c}' but no loop it owns declares it. Remove the grant or declare the need.`);
      }
    }

    const modelTier = emp.model ?? merged.model!;
    const model = overlay.tiers[modelTier] ?? modelTier;
    const utility = overlay.tiers[merged.utility_model!] ?? merged.utility_model;

    // reports_to compiles into delegation allowlists — the org chart made real.
    const reports = Object.entries(overlay.employees)
      .filter(([, e]) => core.archetypes[e.archetype]?.reports_to === id)
      .map(([subId]) => subId);

    agents[id] = {
      id,
      name: emp.name,
      identity: { name: emp.name },
      workspace: `${wsRoot}/agents/${id}`,
      agentDir: `${wsRoot}/agents/${id}/.agent`,
      model,
      utilityModel: utility,
      sandbox: { mode: merged.sandbox?.mode, backend: "docker", workspaceAccess: merged.sandbox?.workspace_access },
      // An explicit list REPLACES the runtime defaults entirely, which is why
      // every agent gets an exhaustive one and inherits nothing.
      skills: Object.entries(loops).filter(([, p]) => p.owner === id).map(([n]) => n),
      tools: (() => {
        const semantic = merged.tools?.profile ?? "minimal";
        const mapped = PROFILE_MAP[semantic];
        if (!mapped) { fail(`agent '${id}' uses unknown tool profile '${semantic}' (known: ${Object.keys(PROFILE_MAP).join(", ")})`); return {}; }
        // Union of the profile's baseline denies and the agent's own — deny wins.
        const deny = [...new Set([...mapped.deny, ...(merged.tools?.deny ?? [])])];
        return { profile: mapped.profile, deny, ...(merged.tools?.allow ? { allow: merged.tools.allow } : {}) };
      })(),
      // Per-agent subagents only carries the allowlist; the numeric caps live in
      // agents.defaults per the shipped schema.
      subagents: { allowAgents: reports, requireAgentId: true },
      ...(merged.system_agent ? { default: true } : {}),
    };

    budgets[id] = { ...(core.defaults.budget as Budget), ...(arch.budget ?? {}) };

    for (const c of credentials) {
      const loopName = Object.entries<any>(loops).find(([, p]) => p.owner === id && (p.capabilities?.credentials ?? []).includes(c))?.[0];
      if (loopName) {
        skills[loopName] = skills[loopName] ?? { env: {} };
        skills[loopName].env[c] = `\${${c}}`;   // resolved from the gitignored .env
      }
    }
  }

  // ---- Slack bindings ----------------------------------------------------
  // Routing is deterministic and most-specific-first. Every bound channel gets
  // requireMention so the agent does not respond to every message in a shared
  // channel — in a workspace with humans that is the difference between a
  // colleague and a nuisance.
  const bindings: any[] = [];
  const slackChannels: Record<string, any> = {};
  for (const [id, emp] of Object.entries(overlay.employees)) {
    for (const ch of emp.slack_channels ?? []) {
      if (!/^C[A-Z0-9]+$/.test(ch)) {
        fail(`employee '${id}' has slack channel '${ch}' — use the immutable channel ID (C...), not the name`);
        continue;
      }
      bindings.push({ agentId: id, comment: `#${ch} -> ${id}`, match: { channel: "slack", peer: { kind: "channel", id: ch } } });
      slackChannels[ch] = { enabled: true, requireMention: true };
    }
  }

  if (failures.length) throw new CompileError(failures);

  const outDir = join(companyDir, "generated");
  mkdirSync(outDir, { recursive: true });
  const src = "org.yaml + org.overlay.yaml + loops/*/policy.yaml";

  // NOTE: `agents.list` is an ARRAY and `id` is required. The published docs
  // still show an `agents.entries` map — the shipped JSON schema is the
  // authority, and it disagrees. Re-check on every image bump; this is exactly
  // the fast-upstream tax PLAN.md budgets for.
  const sub = core.defaults.subagents as any ?? {};
  emit(join(outDir, "agents.json5"), {
    defaults: {
      subagents: {
        maxConcurrent: sub.max_concurrent,
        maxChildrenPerAgent: sub.max_children_per_agent,
        maxSpawnDepth: sub.max_spawn_depth,
      },
    },
    list: Object.values(agents),
  }, src);
  emit(join(outDir, "skills.json5"), { entries: skills }, src);
  emit(join(outDir, "bindings.json5"), bindings, src);

  // Provider + model catalogue. The API KEY is never emitted — only a ${VAR}
  // reference that the runtime resolves from the gitignored .env. Costs are
  // declared here so the runtime's own accounting agrees with lib/budget.
  if (overlay.provider) {
    const p = overlay.provider;
    const modelIds = [...new Set(Object.values(overlay.tiers))];
    emit(join(outDir, "models.json5"), {
      providers: {
        [p.id]: {
          api: p.api,
          baseUrl: p.base_url,
          apiKey: `\${${p.api_key_env}}`,
          models: modelIds.map((full) => {
            const id = full.startsWith(`${p.id}/`) ? full.slice(p.id.length + 1) : full;
            return { id, name: id, contextTokens: MODEL_CONTEXT[full] ?? 128_000, cost: MODEL_COST[full] ?? UNPRICED };
          }),
        },
      },
    }, src);
  }
  emit(join(outDir, "budgets.json"), { perLoop: Object.fromEntries(Object.entries<any>(loops).map(([n, p]) => [n, p.budget])), perAgent: budgets }, src);

  return { agents: Object.keys(agents).length, loops: Object.keys(loops).length };
}

export { CompileError };

// ---- CLI -----------------------------------------------------------------
// Guarded so tests can import compile() without triggering a run.
const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (invokedDirectly) {
const args = process.argv.slice(2);
const companyDir = resolve(args.find((a) => !a.startsWith("--")) ?? "../tepui-company");
try {
  const r = compile(companyDir);
  console.log(`compiled ${r.agents} agents, ${r.loops} loops -> ${companyDir}/generated/`);
} catch (e) {
  if (e instanceof CompileError) {
    console.error(`\ncompile FAILED — refusing to emit:\n`);
    for (const f of e.failures) console.error(`  ✗ ${f}`);
    console.error();
    process.exit(1);
  }
  throw e;
}
}
