/**
 * tepui — org compiler
 *
 * org.yaml (core archetypes) + org.overlay.yaml (company) + loops/(*)/policy.yaml
 *   -> <company>/generated/{agents,skills,hooks,plugins}.json5 + budgets.json
 *
 * Two properties make this load-bearing rather than convenient:
 *
 *   1. The output is COMMITTED, so a permission change is a reviewable PR diff.
 *      `--check` asserts the compiler is idempotent (CI runs it, then
 *      `git diff --exit-code`).
 *   2. It FAILS CLOSED. Every invariant below refuses to emit rather than
 *      emitting something permissive. A compiler that warns is a compiler that
 *      gets ignored.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const HERE = dirname(fileURLToPath(import.meta.url));
const CORE = process.env.TEPUI_CORE ? resolve(process.env.TEPUI_CORE) : resolve(HERE, "../..");

type Sandbox = { mode: "off" | "non-main" | "all"; workspace_access: "none" | "ro" | "rw" };
type Budget = { per_run_usd: number; per_day_usd: number };

type Archetype = {
  title: string;
  reports_to?: string;
  system_agent?: boolean;
  model?: string;
  utility_model?: string;
  sandbox?: Sandbox;
  sandbox_justification?: string;
  reads_untrusted_input?: boolean;
  tools?: { profile: string; deny?: string[]; allow?: string[] };
  credentials?: string[];
  budget?: Budget;
  subagents?: Record<string, number>;
};

class CompileError extends Error {
  failures: string[];
  constructor(failures: string[]) {
    super(`${failures.length} invariant violation(s)`);
    this.failures = failures;
  }
}

const readYaml = <T,>(p: string): T => parseYaml(readFileSync(p, "utf8")) as T;

/** JSON5-ish emitter: plain JSON is valid JSON5, plus a provenance banner. */
function emit(path: string, value: unknown, source: string) {
  const banner =
    `// GENERATED by runtime/openclaw/compile.ts — DO NOT EDIT BY HAND.\n` +
    `// Source: ${source}\n` +
    `// Edit the source and re-run \`pnpm compile\`. This file is committed so\n` +
    `// that permission changes show up as a reviewable diff.\n`;
  writeFileSync(path, banner + JSON.stringify(value, null, 2) + "\n");
}

export function compile(companyDir: string) {
  const failures: string[] = [];
  const fail = (msg: string) => failures.push(msg);

  const core = readYaml<{ defaults: Partial<Archetype>; archetypes: Record<string, Archetype>; tiers: Record<string, unknown> }>(
    join(CORE, "org.yaml"),
  );
  const overlay = readYaml<{
    tiers: Record<string, string>;
    employees: Record<string, { archetype: string; name: string; model?: string; channels?: string[]; credentials?: string[] }>;
    loops: Record<string, { enabled: boolean }>;
  }>(join(companyDir, "org.overlay.yaml"));

  // ---- loops -------------------------------------------------------------
  const loopsDir = join(CORE, "loops");
  const loops: Record<string, any> = {};
  for (const name of readdirSync(loopsDir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)) {
    const policyPath = join(loopsDir, name, "policy.yaml");
    if (!existsSync(policyPath)) {
      fail(`loop '${name}' has no policy.yaml — every loop must declare its capabilities`);
      continue;
    }
    loops[name] = readYaml(policyPath);

    // INVARIANT: approvals must have a workflow that implements them.
    const approvals = loops[name].approvals ?? [];
    if (approvals.length > 0) {
      const wf = join(CORE, "runtime/openclaw/workflows", `${name}.lobster.yaml`);
      if (!existsSync(wf)) {
        fail(`loop '${name}' declares ${approvals.length} approval(s) but ${wf.replace(CORE + "/", "")} does not exist`);
      }
    }
  }

  // Credentials actually used, by owning agent.
  const credentialsNeededBy = new Map<string, Set<string>>();
  for (const [loopName, policy] of Object.entries<any>(loops)) {
    const owner = policy.owner;
    if (!owner) { fail(`loop '${loopName}' declares no owner agent`); continue; }
    const set = credentialsNeededBy.get(owner) ?? new Set<string>();
    for (const c of policy.capabilities?.credentials ?? []) set.add(c);
    credentialsNeededBy.set(owner, set);
  }

  // ---- agents ------------------------------------------------------------
  const agents: Record<string, any> = {};
  const budgets: Record<string, Budget> = {};
  const skills: Record<string, any> = {};

  for (const [id, emp] of Object.entries(overlay.employees)) {
    const arch = core.archetypes[emp.archetype];
    if (!arch) { fail(`employee '${id}' references unknown archetype '${emp.archetype}'`); continue; }

    const merged: Archetype = { ...core.defaults, ...arch };
    const credentials = emp.credentials ?? arch.credentials ?? [];

    // INVARIANT 1: an explicit sandbox block, always. The upstream docs
    // contradict each other on the default, so we never inherit one.
    if (!merged.sandbox?.mode || !merged.sandbox?.workspace_access) {
      fail(`agent '${id}' has no explicit sandbox block (mode + workspace_access). Never rely on the runtime default.`);
    }

    // INVARIANT 2: sandbox:off is an escape hatch that must be argued for.
    if (merged.sandbox?.mode === "off" && !merged.sandbox_justification) {
      fail(`agent '${id}' sets sandbox.mode=off without a sandbox_justification`);
    }

    // INVARIANT 3 — the intake invariant. Untrusted input and credentials must
    // never coexist in one agent. This is the whole prompt-injection defence.
    if (merged.reads_untrusted_input) {
      if (credentials.length > 0) {
        fail(`agent '${id}' reads untrusted input but holds credentials [${credentials.join(", ")}]. An injection here would control them.`);
      }
      if (merged.sandbox?.mode !== "all" || merged.sandbox?.workspace_access !== "none") {
        fail(`agent '${id}' reads untrusted input and must run sandbox.mode=all with workspace_access=none`);
      }
      const denied = new Set(merged.tools?.deny ?? []);
      for (const t of ["exec", "write", "edit", "message", "web_fetch", "browser"]) {
        if (!denied.has(t)) fail(`agent '${id}' reads untrusted input and must deny '${t}'`);
      }
    }

    // INVARIANT 4: no credential grant broader than what its loops actually use.
    const needed = credentialsNeededBy.get(id) ?? new Set<string>();
    for (const c of credentials) {
      if (!needed.has(c)) {
        fail(`agent '${id}' is granted '${c}' but no loop it owns declares it. Remove the grant or declare the need.`);
      }
    }

    const modelTier = emp.model ?? merged.model!;
    const model = overlay.tiers[modelTier] ?? modelTier;
    const utility = overlay.tiers[merged.utility_model!] ?? merged.utility_model;

    // reports_to compiles into delegation allowlists — the org chart made real.
    const reports = Object.entries(overlay.employees)
      .filter(([, e]) => core.archetypes[e.archetype]?.reports_to === id)
      .map(([subId]) => subId);

    agents[id] = {
      name: emp.name,
      identity: { name: emp.name },
      workspace: `./tepui/agents/${id}`,
      agentDir: `./tepui/agents/${id}/.agent`,
      model,
      utilityModel: utility,
      sandbox: { mode: merged.sandbox?.mode, backend: "docker", workspaceAccess: merged.sandbox?.workspace_access },
      // An explicit list REPLACES the runtime defaults entirely, which is why
      // every agent gets an exhaustive one and inherits nothing.
      skills: Object.entries(loops).filter(([, p]) => p.owner === id).map(([n]) => n),
      tools: { profile: merged.tools?.profile, deny: merged.tools?.deny ?? [], ...(merged.tools?.allow ? { allow: merged.tools.allow } : {}) },
      subagents: {
        allowAgents: reports,
        maxConcurrent: merged.subagents?.max_concurrent,
        maxChildrenPerAgent: merged.subagents?.max_children_per_agent,
        maxSpawnDepth: merged.subagents?.max_spawn_depth,
      },
      ...(merged.system_agent ? { systemAgent: true } : {}),
    };

    budgets[id] = { ...(core.defaults.budget as Budget), ...(arch.budget ?? {}) };

    for (const c of credentials) {
      const loopName = Object.entries<any>(loops).find(([, p]) => p.owner === id && (p.capabilities?.credentials ?? []).includes(c))?.[0];
      if (loopName) {
        skills[loopName] = skills[loopName] ?? { env: {} };
        skills[loopName].env[c] = `\${${c}}`;   // resolved from the gitignored .env
      }
    }
  }

  if (failures.length) throw new CompileError(failures);

  const outDir = join(companyDir, "generated");
  mkdirSync(outDir, { recursive: true });
  const src = "org.yaml + org.overlay.yaml + loops/*/policy.yaml";
  emit(join(outDir, "agents.json5"), { entries: agents, ownership: "explicit" }, src);
  emit(join(outDir, "skills.json5"), { entries: skills }, src);
  emit(join(outDir, "hooks.json5"), { entries: {} }, src);
  emit(join(outDir, "plugins.json5"), { entries: { tepui: { path: "./tepui-core/runtime/openclaw/plugin" } } }, src);
  emit(join(outDir, "budgets.json"), { perLoop: Object.fromEntries(Object.entries<any>(loops).map(([n, p]) => [n, p.budget])), perAgent: budgets }, src);

  return { agents: Object.keys(agents).length, loops: Object.keys(loops).length };
}

export { CompileError };

// ---- CLI -----------------------------------------------------------------
// Guarded so tests can import compile() without triggering a run.
const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (invokedDirectly) {
const args = process.argv.slice(2);
const companyDir = resolve(args.find((a) => !a.startsWith("--")) ?? "../tepui-company");
try {
  const r = compile(companyDir);
  console.log(`compiled ${r.agents} agents, ${r.loops} loops -> ${companyDir}/generated/`);
} catch (e) {
  if (e instanceof CompileError) {
    console.error(`\ncompile FAILED — refusing to emit:\n`);
    for (const f of e.failures) console.error(`  ✗ ${f}`);
    console.error();
    process.exit(1);
  }
  throw e;
}
}
